name: Reusable wf
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployed artifact
        required: true
        default: dist
        type: string
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: result of the deploy
        value: ${{jobs.reusable.outputs.outcome}}
jobs:
  reusable:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
      - name: Check content
        run: ls
      - name: Output Infos
        run: echo "Deploy...."
      - name: Set result output
        id: set-result
        run: echo 'step-result=success' >> $GITHUB_OUTPUT
